### ISSUE TITLE
how to set up your glide version？

### ISSUE THREAD

**Issue by Leijingtian** [xkeyideal/glide#2]
请问怎么能够安装您这个版本的glide呢，我也是windows10系统，能不能再readme中补充下配置的方法。用官方的glide无法识别base指令

**Comment by xkeyideal** [comment]
你是指设置第三包的版本号么？

**Comment by Leijingtian** [comment]
首先引用您的原文如下:
针对这个问题，我的解决方案是修改glide的mirror命令的相关代码，添加--base。。。。操作方法如下：glide mirror set https://golang.org/x/sys/unix https://github.com/golang/sys --base golang.org/x/sys
glide get golang.org/x/sys/unix
然后说我想请教的问题:
您修改了glide的mirror命令的相关代码，也就是说必须使用您改进的glide才能执行添加––base的操作对吧？那么如何安装您这个版本的glide呢？是要对您github上代码进行复制到本地再make build吗？我现在用的是官方12.3的版本，执行glide mirror set https://golang.org/x/sys/unix https://github.com/golang/sys --base golang.org/x/sys会报错。

**Comment by xkeyideal** [comment]
需要使用我的这个代码才能使用--base，没有给官方提pr，只有国内才有这种问题
